spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/money_tracker
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update            # Hibernate creates/updates tables from @Entity classes
    show-sql: true
